### ISSUE TITLE
Match on presence of key

### ISSUE THREAD

**Issue by Koleok** [z-pattern-matching/z#16]
My most common use case is matching on the presence of a key in an object and binding a variable to it de-structured style, I noticed this idea made it into the [tc39 pattern matching proposal](https://github.com/tc39/proposal-pattern-matching/blob/master/README.md#object-patterns) and was wondering if you had plans to implement anything similar in `z`?

_example from proposal:_
```js
match (obj) {
    { x }: /* match an object with x */,
    { x, ... y }: /* match an object with x, stuff any remaining properties in y */,
    { x: [] }: /* match an object with an x property that is an empty array */,
    { x: 0, y: 0 }: /* match an object with x and y properties of 0 */
}
```

I'd be glad to take a crack at it and send a PR if not 😀

**Comment by leonardiwagner** [comment]
Hi @Koleok , it'd be awesome!

I'm looking to implement the good ideas from [tc39 pattern matching proposal](https://github.com/tc39/proposal-pattern-matching/blob/master/README.md#object-patterns) on `z` indeed, a PR with that feature is welcomed

**Comment by bySabi** [comment]
I'm looking this too. What you think about this test examples:
```  it('should match object key', () => {
    const result = z({ x:1, y:1 })(
      ({x}) => true
      ({x, y}) => true,
      ({x, y, z}) => false
    )

    result.should.equal(true)
  })

  it('should match object key value comparison', () => {
    const result = z({ x:1, y:1 })(
      ({x = 2}) => false,
      ({x = 1}) => true,
      ({y = 1}) => false,
      ({x = 1, y = 1}) => true,
      ({x = 2, y = 2}) => true,
      ({x = 1, y = 1, z = 1}) => false
    )

    result.should.equal(true)
  })
```

**Comment by bySabi** [comment]
@leonardiwagner  if you agre with test and syntax I can try to make an implementation

**Comment by leonardiwagner** [comment]
@bySabi I understood @Koleok will work on the presence key feature, let's wait him for a while? However your [rest parameters](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/rest_parameters) idea is very good and you can start implement indeed.

The current syntax also matches and get the object, as:

```javascript
const person = { name: 'John' }
matches(person)(
  (x = { name: 'John'}) => console.log("name is " + x.name)
)
```

Honestly I don't see any advantage having:

```javascript
const person = { name: 'John' }
matches(person)(
  (x = { name: 'John'}, ...xs) => console.log("name is john, rest is: " + xs)
)
```

But can be a start to implement your proposed syntax which don't assign a variable to matched pattern and use the rest parameters:
```javascript
const person = { name: 'John' }
matches(person)(
  ({name = 'John'}, ...xs) => console.log("name is john, rest is: " + xs)
)
```

I'd be good to [rest parameters](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/rest_parameters) also works with arrays, though I don't have a good idea right now 😄 

I'm using [js-function-reflector](https://www.npmjs.com/package/js-function-reflector), it's a small lib however is the best I found for ES2015 function reflection, though I didn't tested how good it read the rest parameters.
**Important:** I think latest version with important bugfixes is not published on npm, that's why it's a git reference on package.json , good luck !

**Comment by bySabi** [comment]
> @bySabi I understood @Koleok will work on the presence key feature, let's wait him for a while? However your rest parameters idea is very good and you can start implement indeed.

OK!  this feature need more consensus before start to code it. 
@Koleok what you think about propose sintax?

> The current syntax also matches and get the object, as:
```
const person = { name: 'John' }
matches(person)(
  (x = { name: 'John'}) => console.log("name is " + x.name)
)
```
Probably this will continue working. 
But,  IMO, this look better, more sense:
```
const person = { name: 'John' }
matches(person)(
  ({ name:  'John'}) => console.log("name is " + name)
)
```
- We take advantage of destructuring
- We we get ride of 'x' var
- We can cover a use-case that is not posible with ( x = { name: 'John })  sintax, `matching` only for a **key**  object, say: `({ name } = > console.log(name)`.   You cannot do this `(x = {name}) => console.log(name)`  

> But can be a start to implement your proposed syntax which don't assign a variable to matched pattern and use the rest parameters:
```
const person = { name: 'John', lastName: 'Connor',  age: 15  }
matches(person)(
  ({name = 'John'}, ...xs) => console.log(`name is ${name}, lastName ${xs.lastName), age ${xs.age}`)
)
```
We don´t need assign vars to matched and `...xs` will be a object with left keys.

**Comment by bySabi** [comment]
Probably rest is not needed and `({name = 'John'}, ...xs)` become `({name = 'John'}, xs)`
```
const person = { name: 'John', lastName: 'Connor',  age: 15  }
matches(person)(
  ({name = 'John'}, xs) => console.log(`name is ${name}, lastName ${xs.lastName), age ${xs.age}`)
)
```

**Comment by bySabi** [comment]
We could add too a `when` function for `guard` cases like in [Exilir Guards](https://hexdocs.pm/elixir/master/guards.html)
Ex:
```
...
const when = require('z').when;

matches(4)(
  (x) => when(x > 3) => console.log('maybe 4'),
  (0) => console.log('zero'),
  (x) => when(x < 0) => console.log('negative'),
  (x = 3) => console.log('three!!')
)
```

Probably this should go to a new `enhancement` issue

**Comment by Koleok** [comment]
@bySabi you were busy here! I took an initial crack at this, which works with arbitrarily nested destructuring as a pattern, but does not yet support patterns like 

- [ ] `({ x: Boolean }) => x` 
- [ ] `({ x: 'literal string' }) => x`

In my opinion these would need to work, what do you guys think?

I am obviously in favor of dropping the default arg approach that is currently ubiquitous in this library just because it is not really possible to do `key presence matching` in that way.

**Comment by Koleok** [comment]
Also @leonardiwagner I modified some folder structure and put `prettier` in place for commit hooks, but it looks as though you have done some work since then making my PR here pretty conflict-y, I will take a look at that later tonight and try and post a version that can actually be merged.

**Comment by leonardiwagner** [comment]
@bySabi looks good, let's open another issue for guards!

> You cannot do this (x = {name}) => console.log(name)

just wondering, why we can't do this?

**Comment by leonardiwagner** [comment]
@Koleok I merged a PR with prettier already, just take a look while merging, prettier is restricted to `src` only, because I doesn't look good with pattern matching syntax

**Comment by Koleok** [comment]
@leonardiwagner In regards to

> You cannot do this (x = {name}) => console.log(name)

Its because the default value has to be something valid, and in order for that [`object shorthand`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015) syntax to work there would need to be an existing variable called `name` in scope, which would defeat the purpose because we are trying to bind that name into the handler.

**Comment by leonardiwagner** [comment]
@Koleok I'm not sure about that, because in your example `x` isn't declared also and works. The `z` approach is to reflect parameters (both `x` and `name`), stores values in a memory object, and latter apply to the function (in your eg. => { console.log(name) })

**Comment by bySabi** [comment]
I also thought it would not work but it does.
```
const fn = (x = {name}) => console.log(x)
...
fn() // -> { name: "" }
```

**Comment by bySabi** [comment]
`name` is not a parameter , is a key of a `object literal`, a value.

**Comment by Koleok** [comment]
Wow this [`really does work`](https://koleok.github.io/repl/#?const%20obj%20%3D%20%7B%20name%20%7D%0A%0Aobj) and reveals a behavior i never knew about before.

Looks like my initial implementation could get simpler then.

**Comment by leonardiwagner** [comment]
@Koleok yes, be free to send another PR. Don't forget about pulling `master` before, and the build is breaking due lack of coverage but nevermind, I'm working on this.

@bySabi sure, but the whole object `{ name }` is and is (or at least should be!) reflected also

**Comment by leonardiwagner** [comment]
Guys, I'm going to close this issue, it's becoming huge and also this feature is already implemented.

@Koleok Thank you for your contribution. Though is working, it'd be good to try to use  the `js-function-reflection` instead implement reading by itself to reduce project complexity, though is very good solution, congrats!

@bySabi you can open another issue / PR to implement your idea about the rest-parameters, looks promising.

**Comment by Koleok** [comment]
@leonardiwagner thanks 😉 I actually did rely on the output of `js-function-reflection`, but it just didn't seem to be fully equipped to handle a destructured object signature _(returns something like `['{a', 'b:{', 'c']` for the reflected `args` array)_, thus the roundabout silliness of [this](https://github.com/z-pattern-matching/z/blob/master/src/matchObject.js#L8) 😂

**Comment by leonardiwagner** [comment]
@Koleok oh that's true! I'll try to ping that project owner, thank you again!

**Comment by leonardiwagner** [comment]
@Koleok bug reported at: https://github.com/arrizalamin/js-function-reflector/issues/6 , the library code is kind of simple, maybe you take a look easily how to solve, otherwise I can take a look on weekend.

**Comment by bySabi** [comment]
I'm coding and researching a parameters parser for `z`. 
IMO fixing `js-function-reflector`  for `z` is not the way to go.

 Let me see what I got at end of week.

**Comment by Koleok** [comment]
@bySabi I think I agree here, there are deeper problems like the fact that everything gets destroyed if this library gets picked up and transpiled/bundled since `babel` renames all the destructured args like `_ref2`

**Comment by bySabi** [comment]
`babel` is a problem. I will take a look when finnish the parser and matcher, `guards` include , :).
But it will more easy if we stay with current sintax for objects, say `(x = { name }) =>  name`

I need a more time to commit an **alpha** casue I'm rewriting all from scratch.
