### ISSUE TITLE
Not work with Babel

### ISSUE THREAD

**Issue by bySabi** [z-pattern-matching/z#22]
Transformed code with Babel not work.

Probably is due this is not set: from `js-function-reflector` doc:

```
var functionReflector = require('js-function-reflector');
// If you are using babel transpiler
functionReflector = reflector.compiler('babel-preset-es2015');
```

**Comment by bySabi** [comment]
I think this must be solve explicitly:

```
const matcher = require('z')    // native ES6
```
AND

```
var matcher = require('z/babel')   // Babel compliant
```

**Comment by leonardiwagner** [comment]
@bySabi I didn't start to work on babel, and I don't know to work with him yey, I have a question:

when you write a match like this:
```javascript
matches(1)(
  (x = { name: String})  => console.log('hey!'),
  (x = Number) => console.log('ya!')
)
```

it'll transpile as:
```javascript
matches(1)(function () {
  var x = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : { name: String };
  return console.log('hey!');
}, function () {
  var x = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : Number;
  return console.log('ya!');
});
```

is there a way to receive the written code instead the transpiled one in `z`?

**Comment by bySabi** [comment]
> is there a way to receive the written code instead the transpiled one in z?

I'm afraid this is not posible, maybe with a `babel-plugin` and making `annotations` in matches function patterns. But I think is not worth it.
The `js-function-reflector` approach is more simple, [babel-preset-es2015-reflector]( https://github.com/arrizalamin/js-function-reflector/blob/master/babel-preset-es2015-reflector/index.js#L3) parse tranformed functions and extract `default` params.

`z` need the fastest **function** parameter extraction code. The performance of this library will relay on this part. We must create a customized function parameter parser, aka `reflector`, and left current solution, `js-function-reflector`

I started  to coding one from scratch with benchmark comparison vs current `reflector`. It  will cover `babel` case too.

**Comment by leonardiwagner** [comment]
@bySabi ok, I wasn't aware how`babel-preset-es2015` works, I'm gonna take a look later on this too, thank you.

**Comment by bySabi** [comment]
I will follow another path where Babel is not a problem.
