### ISSUE TITLE
Current problem with `z`

### ISSUE THREAD

**Issue by bySabi** [z-pattern-matching/z#23]
When I found `z` I wanted to improve it, bringing pattern matching to javascript will be a breakthrough. First of all I wanted to understand how it was implemented and what is better than reimplement it from scratch. A few days later I abandoned the idea because in my opinion this library has no future. I report the problems I have encountered.

`z` bases its logic on functions **"reflection?"**. The trick of reflection is to convert the function to string, `Function.toString()` and then extract the match patterns from there. You can make an acceptably fast parser to save performance problems but this is not the main problem.

When we convert the function to string to extract the **default values** ​​what we are doing is "serialize" the function. The problem is when we "deserialize", for this we need to use **eval** that is slow and has serious security problems and the worst thing is that we can only deserialize the build-in types, forget about doing match of something like `(x = MyType) => x`

The other option is to create a transform plugin for Babel similar to sparkler (made with sweet.js) https://github.com/natefaubion/sparkler
But I think it's best for the bright minds of https://github.com/tc39/proposal-pattern-matching/blob/master/README.md#object-patterns to do so.

I for my part have a third option and wanted to share it here in case `z` crew want to follow this path, before make a separate library. I share a piece of code to see how it might look. There are no reflections or parsers, only vanilla js and the sintax is different 

```
function matcher(v) {
    return function (...funcs) {
        const firstCall = funcs.map(fn => fn())
        for (let i = 0; i < firstCall.length; i++) {
            const [fn, x] = firstCall[i];
         
          // TODO: this the most simply matcher
          // we need dedicate matchers for all javascript types
          if (v === x) {
                return fn(x)
            }
        
      }
    }
}

function match(x, ...y) {
  return function(fn) {
     return [fn, x, ...y];
  }
}


// New sintax
const a = matcher(5)(
    (x) => match(x)(console.log),
    (x = 3) => match(x)(console.log),
    (x = 5) => match(x)(console.log)
)
```

What is your opinion/decision ?? @leonardiwagner @Koleok

**Comment by leonardiwagner** [comment]
Hi @bySabi,  `z` is not about parsing/reflecting javascript code, not at all. There is no such code as `eval` or `.toString()` which you mentioned, `z` only orchestrates reflected data to achieve pattern matching feature. Currently we are using [some library](https://github.com/arrizalamin/js-function-reflector) to reflects javascript functions and probably there is your disappointment.

So, 2/3 of your argument is about that reflection library, which `z` is not dependent, we can change to a better one, use a new approach. Just say a new better approach, and let's do it. So I won't consider these arguments, is that okay for you?

About the last one part of your argument, `z` was born precisely to just run easy and go in any project, without any huge dependency as sweet.js ([which author himself still consider in experiment and under heavy work](https://medium.com/@disnet/sweetening-syntactic-abstractions-e615ab87f2dd)) , and ironically has a bunch of performance issues you are afraid of. If your idea of transformer still makes `z` run under only `npm install z` , let's do it and place that instead the currently library, and surely I'll make a contribution too.

**Comment by bySabi** [comment]
@leonardiwagner I had been researching and make a little trial&error for a couple of days and I can say there are not  function **reflection** in current javascript, just the `toString()` trick. See your self: https://github.com/arrizalamin/js-function-reflector/blob/master/index.js#L10

But to me real problem is **deserialize**  function default values with *eval*: https://github.com/arrizalamin/js-function-reflector/blob/master/argument_parser.js#L119

The real problem here is that we cannot deserialize **Custom Types**

**NOTE**: I remove `js-function-reflector` and do one **function param parser** but hit the same wall 

The 2nd path is a Babel transform step but  is a matter of time that `tc39/proposal-pattern-matching`  guys make one.

And the 3rd option, is breaking change, sintax will be something like this:
```
// New sintax
const a = matcher(5)(
    (x) => match(x)(console.log),
    (x = 3) => match(x)(console.log),
    (x = 5) => match(x)(console.log)
)
```
I know how add guards and wanna add a comparator interface for custom Types

What I want to know if `z` will follow the 3rd option, breaking changes include or will still follow current `reflection` path?

**Comment by leonardiwagner** [comment]
@bySabi what I tried to explain is, there is such issues on `js-function-reflector` indeed, but it's not `z` issues. If we want to improve, let's do it on js-function-reflector or create a new lib to send reflection data to `z`.

The problem about **Custom Types** is: when user create types, he creates in a specific scope. When z `match` function is invoked, we don't share the same scope of declared **Custom Types**, that's why is not a matter of function reflection. (If user set his Custom Type in global, it works 😜)

Do you have any idea to solve that? I can't think anything but the user need to inject his custom types to `z`.

How do you achieve that solution with you 3rd option syntax propose? I didn't get. Syntax change is okay now since z 1.0 was not officially released.

**Comment by arrizalamin** [comment]
Hi @bySabi and @leonardiwagner, I'm a creator of [js-function-reflector](https://github.com/arrizalamin/js-function-reflector/) and also interested in `z`. I think there is a way to remove _eval_ from my function reflector, but that will need big changes in the parser to save key and value from array/object argument. And a suggestion to your 3rd option is to use ES6 [Symbol](https://developer.mozilla.org/id/docs/Web/JavaScript/Reference/Global_Objects/Symbol) so the matcher parameter won't have the same value with "all" parameter like this.
```javascript
const allSym = Symbol('ALL')
var matcher = function(v) {
    return function (...funcs) {
        const firstCall = funcs.map(fn => fn())
        for (let i = 0; i < firstCall.length; i++) {
            const [fn, x] = firstCall[i];

          if (v === x) {
                return fn(x)
            }
          if (x === allSym) {
            return fn(v)
          }
        
      }
    }
}
Object.defineProperty(matcher, "all", {value: allSym})

function match(x, ...y) {
  return function(fn) {
     return [fn, x, ...y];
  }
}


// New sintax
const a = matcher(5)(
    (x = matcher.all) => match(x)(console.log),
    (x = 3) => match(x)(console.log),
    (x = 5) => match(x)(console.log)
)
```

**Comment by bySabi** [comment]
> @bySabi what I tried to explain is, there is such issues on js-function-reflector indeed, but it's not z issues. If we want to improve, let's do it on js-function-reflector or create a new lib to send reflection data to z.

If a `z` problem cause it is build on the premise that `function`  reflexion is posible in javascript and is not. I just a trick.

> The problem about Custom Types is: when user create types, he creates in a specific scope. When z match function is invoked, z runs in a new scope which don't share the caller scope (which was declared Custom Type), that's why is not a matter of function reflection. (If user set his Custom Type in global, it works 😜 , as Date is in global)
Do you have any idea to solve that? I can't think anything but the user need to inject his custom types to z.

You **hit the wall**:
* You cannot suggest to users that put his **identifiers** in the global context.
* You cannot inject a whole context on `eval`/ `new Function` scopes
* All idetifers involved will need to be inject one by one the `eval` context

> When z match function is invoked, z runs in a new scope which don't share the caller scope (which was declared Custom Type), that's why is not a matter of function reflection. (

This is not correct,  is the same scope. Here `CustomType` is the same scope of `z`. But we must put in global scope for make it works
```
function CustomType() {}
const custom = new CustomType();

// node global: we need this!!
global.CustomType = CustomType 

z(custom)(
  (x = CustomType) => console.log('custom'),
  (x) => console.log('any')
)
```
This will fail without explicit global with:  `ReferenceError` exception...
```
ReferenceError: CustomType is not defined
    at eval (eval at Parser.pushBuffer (/Users/flx/Desktop/wip/z/node_modules/js-function-reflector/argument_parser.js:89:24)
```

> How do you achieve that solution with you 3rd option syntax propose? I didn't get. Syntax change is okay now since z 1.0 was not officially released.

```
function match(x, ...y) {
  return function(fn) {
     return [fn, x, ...y];
  }
}


// New sintax
const a = matcher(5)(
    (x = matcher.all) => match(x)(console.log),
    (x = 3) => match(x)(console.log),
    (x = 5) => match(x)(console.log)
)
```

`match` act as a proxy receiving and storing default values cause, Ex: `(x  = 3) => match(x)` is called without arguments.  `match`  return a tuple with the `user function` and all defaults parameters. Then `matcher` compare this values with the argument, `5` in this case. If match, user function is called and interation is stopped(return).

This snippet have  a very simple values comparator. We need comparator for all build-in types.
The core  of matcher will be something like this 10-15 line of code and zillions of time faster than current.

**Comment by bySabi** [comment]
Hi @arrizalamin. I know your code 👍 

Please! tell me,  what is your idea about `eval` replacement. I implemented `default arguments extraction` with **new Function()** beside *eval* but at the end we have the same problem, a different context than the `user context`

I had take note of the `Symbol` suggestion.

Thanks!

**Comment by bySabi** [comment]
@leonardiwagner is fine to you, tomorrow I will continue with the specs of the new sintax and a rough implementation.

**Comment by bySabi** [comment]
@arrizalamin, trick per trick :)

I create this function for detect is we are run in a transformed code environment.  With this your user don´t need configure for Babel, you do transparently.

```
// check is function definition is transformed
// use for detect Babel
const isTransformedFunc = () => /:\s*747/.test(((x = 747) => x).toString())
```

`747` is MAGIC number, don't meen nothing!

**Comment by leonardiwagner** [comment]
> This is not correct, is the same scope. Here CustomType is the same scope of z

@bySabi I'm afraid you are not considering `z` or any library you make will run inside another scope due being inside a module, which is other than user defined Custom Type scope, let's see an example:

someMatch.js
```javascript
module.exports = function(somethingToCompare){
   //problem is here, in this scope, there is no MyCustomType defined
   console.log("is instance of my custom type?", somethingToCompare instanceof MyCustomType)
}
```
index.js
```javascript
var someMatch = require('./someMatch')

class MyCustomType { }
const myInstance = new MyCustomType()

someMatch(myInstance) // will throw MyCustomType not defined error
```

so I don't think you are gonna to achieve CustomType solution just with new syntax either, is a module restriction, or am I misunderstanding something?

**Comment by arrizalamin** [comment]
@bySabi the idea is when a parser finds a string opening (',",`) it will scan until the end of a string and parse that as a string. When it finds a number, use parseFloat() to parse them as a number. We need to make the same thing for regex/symbol/etc. And when it finds an object/array opening ({,[), it will scan all key as a string and all of the previous functions (string,number,regex,etc) to parse the value recursively and rebuilt that object/array with all of the parsed keys and values.

**Comment by bySabi** [comment]
```
module.exports = function(somethingToCompare){
   //problem is here, in this scope, there is no MyCustomType defined
   console.log("is instance of my custom type?", somethingToCompare instanceof MyCustomType)
}
```

When function is called it will throw a  `ReferenceError: MyCustomType is not defined ...`

This the normal behaviour of javascript, scope is lexical. MyCustomType must be defined in the moment of the function is defined nor when is called. 
`this.MyCustomType` is diferent cause scope will resolve in moment it is called.

**Comment by leonardiwagner** [comment]
> `this.MyCustomType` will be diferent cause scope will resolved when is called.

@bySabi can you please write a quick example about this working?

**Comment by bySabi** [comment]
ah!! sorry!!  `this.MyCustomType` not make any sense.

 I was just taking about the diferences between  functions scopes. A correct example will be `this.anyFunction`

**Comment by leonardiwagner** [comment]
@bySabi it's ok, any idea how to solve that? (besides user needing to send us types via injection)

**Comment by bySabi** [comment]
@leonardiwagner, I have no idea. I think it can not be done. That is why close that path and in my opinion, for the best, I have made some progress, I hope to share it in a few days

**Comment by leonardiwagner** [comment]
@bySabi OK, so I'm closing this issue
