### ISSUE TITLE
a unfinnish work ...

### ISSUE THREAD

**Issue by bySabi** [z-pattern-matching/z#24]
Relate to previous issues: https://github.com/z-pattern-matching/z/issues/16 https://github.com/z-pattern-matching/z/issues/22 https://github.com/z-pattern-matching/z/issues/23

I start to research another way to implement pattern matching, I make some progress but I don´t have more time to continue. 

Is really hard to do a rich pattern matching library and retain a user friendly API. IMO create a parallel library to current [tc39/proposal-pattern-matching](https://github.com/tc39/proposal-pattern-matching) is not the way to go. But I think this `unfinnish work`  could be use like a ES5 pollyfil of future `pattern-matching` Babel transform. It seem another developers are made some progress in this direction: https://github.com/Jamesernator/pattern-match

Any way here is the repos of the working implementation. They are two packages:
 * [core-z](https://github.com/bySabi/core-z) is the assertion engine
 * [z](https://github.com/bySabi/z) is the assertion library

Right now the code is working but will need create more assertion functions for match Objects, Arrays, ...

I hadn´t write docs beyond code comments and working test examples, sorry.

I hope this could be useful ...

**Comment by leonardiwagner** [comment]
Cool, but I really didn't get how it could help or solve a problem, actually I didn't get what problem this project are trying to solve, can you explain with more details please?

**Comment by bySabi** [comment]
`core-z` and assertion `z` library solve some problems that have current `z`:
* native ES5 support
* performace. Current `z` relay on to String conversion and regex parse.
* Current `z` don't follow the Open/closed principle. With `core-z` any one can create `assertions/match` functions. With current `z` this must be done throught Pull request.
* `core-z` don't have the scope problems of current `z`, all happends in the same context.
 
This are some of the things I see.

This code is **unfinnish** cause I don´t have more time to add assertion functions to `z` for  **pattern match**  and **bound values extraction** on Object, Arrays, ...

`core-z` engine is done and have the require flexibillity to handle all this kinds of operations.
Is matter of call [createAssertFn](https://github.com/bySabi/z/blob/master/src/is.js#L1) and create it. 

Take a look a test files or `core-z` and `z` too see how is done and how easy is to extend.

**Comment by leonardiwagner** [comment]
> native ES5 support

we have 0.0.7 version which supports es5, also, I didn't see the solution to have same capabilities on es5 in your project

> performace

do you have any metric comparison, or performance hassle while using `z` to properly report this as issue? If your library has **at least same features and runs faster**, then it would be a solution.

> Current z don't follow the Open/closed principle. With core-z any one can create assertions/match functions. With current z this must be done throught Pull request.

OK, I'll check this, feel free to open a PR for that.

> core-z don't have the scope problems of current z, all happens in the same context.

Again, I didn't see the solution about this properly working with same capabilities, could you explain why it work and how it'd work on `z` ?

@bySabi It looks like many of proposed solutions are just hypothetical, it's vague saying "my unfinished work has solutions for `z` problems" if neither of solutions and problems are very well defined.

I will close this until problems or solutions are explicit described.
