### ISSUE TITLE
How is this possible?

### ISSUE THREAD

**Issue by ccorcos** [z-pattern-matching/z#30]
I see you're using `js-function-reflector` but does that mean you need to use `babel-preset-es2015-reflector`?

**Comment by leonardiwagner** [comment]
@ccorcos not directly, it's just a dependency of `js-function-reflector` but we don't use any feature of `babel-preset-es2015-reflector`. We could fork the library and remove that dependency if necessary. Is there any reason to justify that move?

**Comment by ccorcos** [comment]
No, I’m just curious how this works! Are you using Function.toString and
parsing text? How does this work?

**Comment by leonardiwagner** [comment]
Yes, that's the `js-function-reflector` approach. It was very hard to find such lib that works well with lambda, default arguments, and new stuff, any that was the only one I found which works well!

**Comment by ccorcos** [comment]
Isn't it going to break once you use a minifier though?
