### ISSUE TITLE
Suuup

### ISSUE THREAD

**Issue by lucasviola** [z-pattern-matching/z#5]
![Like a boss](http://gifs.joelglovier.com/boss/breakfast-club-sunglasses.gif)

**Comment by leonardiwagner** [comment]
![wassup](https://66.media.tumblr.com/cb8c35e0a012af2c4c9f3eae3be5b171/tumblr_mypng9t8RN1qk0z6co1_500.gif)

this library is not fancy enough, working on it!

**Comment by naomik** [comment]
![mmmmhm](http://i.imgur.com/L4MdYay.gif)

**Comment by leonardiwagner** [comment]
2 years later, [officially released](https://z-pattern-matching.github.io/)!

**Comment by lucasviola** [comment]
Awesome! :D
