### ISSUE TITLE
not matching strings

### ISSUE THREAD

**Issue by leonardiwagner** [z-pattern-matching/z#7]
```javscript
'text'.matches(
      (x = 'text') => 'a'
    )
```

it isn't returning `a` , is throwing `can't match anything for: text` instead

**Comment by leonardiwagner** [comment]
it's failing because we're converting a `string` into an array of `chars` , very bad decision 😢 

we need to remove [this split from string](https://github.com/z-pattern-matching/z/blob/master/src/z.js#L40), however it's breaking the lib, need to fix that!

**Comment by aterribili** [comment]
Any new @leonardiwagner ?

**Comment by leonardiwagner** [comment]
@aterribili I just fixed on #9 

the solution was almost easy, when you match a string, I transformed the string as array of the single string, eg.: `"string"` as `["string"]`  , and another step of verification, if the value is a string, compare as string, and worked 👍 

## please update the lib as **0.0.6**
